server:
  port: 8082

spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanglinqiao/spring-cloud-parent
          search-paths: config-repo
          username: wanglinqiao
          password: Wlq520131

